/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 912955676;

    private String     code;
    private String     name;
    private Integer    bonusPoints;
    private BigDecimal availableMoney;

    public Customer() {}

    public Customer(Customer value) {
        this.code = value.code;
        this.name = value.name;
        this.bonusPoints = value.bonusPoints;
        this.availableMoney = value.availableMoney;
    }

    public Customer(
        String     code,
        String     name,
        Integer    bonusPoints,
        BigDecimal availableMoney
    ) {
        this.code = code;
        this.name = name;
        this.bonusPoints = bonusPoints;
        this.availableMoney = availableMoney;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getBonusPoints() {
        return this.bonusPoints;
    }

    public void setBonusPoints(Integer bonusPoints) {
        this.bonusPoints = bonusPoints;
    }

    public BigDecimal getAvailableMoney() {
        return this.availableMoney;
    }

    public void setAvailableMoney(BigDecimal availableMoney) {
        this.availableMoney = availableMoney;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(bonusPoints);
        sb.append(", ").append(availableMoney);

        sb.append(")");
        return sb.toString();
    }
}
