/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmType implements Serializable {

    private static final long serialVersionUID = -944327572;

    private Integer id;
    private String  name;
    private Integer numberDaysWithSamePrice;
    private Integer defaultBonusPoints;
    private Integer priceTypeId;

    public FilmType() {}

    public FilmType(FilmType value) {
        this.id = value.id;
        this.name = value.name;
        this.numberDaysWithSamePrice = value.numberDaysWithSamePrice;
        this.defaultBonusPoints = value.defaultBonusPoints;
        this.priceTypeId = value.priceTypeId;
    }

    public FilmType(
        Integer id,
        String  name,
        Integer numberDaysWithSamePrice,
        Integer defaultBonusPoints,
        Integer priceTypeId
    ) {
        this.id = id;
        this.name = name;
        this.numberDaysWithSamePrice = numberDaysWithSamePrice;
        this.defaultBonusPoints = defaultBonusPoints;
        this.priceTypeId = priceTypeId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNumberDaysWithSamePrice() {
        return this.numberDaysWithSamePrice;
    }

    public void setNumberDaysWithSamePrice(Integer numberDaysWithSamePrice) {
        this.numberDaysWithSamePrice = numberDaysWithSamePrice;
    }

    public Integer getDefaultBonusPoints() {
        return this.defaultBonusPoints;
    }

    public void setDefaultBonusPoints(Integer defaultBonusPoints) {
        this.defaultBonusPoints = defaultBonusPoints;
    }

    public Integer getPriceTypeId() {
        return this.priceTypeId;
    }

    public void setPriceTypeId(Integer priceTypeId) {
        this.priceTypeId = priceTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmType (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(numberDaysWithSamePrice);
        sb.append(", ").append(defaultBonusPoints);
        sb.append(", ").append(priceTypeId);

        sb.append(")");
        return sb.toString();
    }
}
