/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;

import javax.annotation.Generated;

import jooq.jooqobjects.tables.CustomerFilmRent;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerFilmRentRecord extends UpdatableRecordImpl<CustomerFilmRentRecord> implements Record9<Integer, String, Integer, BigDecimal, Integer, BigDecimal, Integer, LocalDate, LocalDate> {

    private static final long serialVersionUID = 1829402699;

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.customer_code</code>.
     */
    public void setCustomerCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.film_id</code>.
     */
    public void setFilmId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.film_id</code>.
     */
    public Integer getFilmId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.gained_bonus_points</code>.
     */
    public void setGainedBonusPoints(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.gained_bonus_points</code>.
     */
    public Integer getGainedBonusPoints() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.late_return_charge</code>.
     */
    public void setLateReturnCharge(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.late_return_charge</code>.
     */
    public BigDecimal getLateReturnCharge() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.number_rent_days</code>.
     */
    public void setNumberRentDays(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.number_rent_days</code>.
     */
    public Integer getNumberRentDays() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.rent_date</code>.
     */
    public void setRentDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.rent_date</code>.
     */
    public LocalDate getRentDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>video_rental_schema.customer_film_rent.return_date</code>.
     */
    public void setReturnDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>video_rental_schema.customer_film_rent.return_date</code>.
     */
    public LocalDate getReturnDate() {
        return (LocalDate) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, BigDecimal, Integer, BigDecimal, Integer, LocalDate, LocalDate> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, BigDecimal, Integer, BigDecimal, Integer, LocalDate, LocalDate> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.CUSTOMER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.FILM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.GAINED_BONUS_POINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.LATE_RETURN_CHARGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.NUMBER_RENT_DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field8() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.RENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field9() {
        return CustomerFilmRent.CUSTOMER_FILM_RENT.RETURN_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFilmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGainedBonusPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getLateReturnCharge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getNumberRentDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value8() {
        return getRentDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value9() {
        return getReturnDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value2(String value) {
        setCustomerCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value3(Integer value) {
        setFilmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value5(Integer value) {
        setGainedBonusPoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value6(BigDecimal value) {
        setLateReturnCharge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value7(Integer value) {
        setNumberRentDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value8(LocalDate value) {
        setRentDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord value9(LocalDate value) {
        setReturnDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerFilmRentRecord values(Integer value1, String value2, Integer value3, BigDecimal value4, Integer value5, BigDecimal value6, Integer value7, LocalDate value8, LocalDate value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerFilmRentRecord
     */
    public CustomerFilmRentRecord() {
        super(CustomerFilmRent.CUSTOMER_FILM_RENT);
    }

    /**
     * Create a detached, initialised CustomerFilmRentRecord
     */
    public CustomerFilmRentRecord(Integer id, String customerCode, Integer filmId, BigDecimal price, Integer gainedBonusPoints, BigDecimal lateReturnCharge, Integer numberRentDays, LocalDate rentDate, LocalDate returnDate) {
        super(CustomerFilmRent.CUSTOMER_FILM_RENT);

        set(0, id);
        set(1, customerCode);
        set(2, filmId);
        set(3, price);
        set(4, gainedBonusPoints);
        set(5, lateReturnCharge);
        set(6, numberRentDays);
        set(7, rentDate);
        set(8, returnDate);
    }
}
