/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects;


import javax.annotation.Generated;

import jooq.jooqobjects.tables.Customer;
import jooq.jooqobjects.tables.CustomerFilmRent;
import jooq.jooqobjects.tables.Film;
import jooq.jooqobjects.tables.FilmType;
import jooq.jooqobjects.tables.PriceType;
import jooq.jooqobjects.tables.records.CustomerFilmRentRecord;
import jooq.jooqobjects.tables.records.CustomerRecord;
import jooq.jooqobjects.tables.records.FilmRecord;
import jooq.jooqobjects.tables.records.FilmTypeRecord;
import jooq.jooqobjects.tables.records.PriceTypeRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>video_rental_schema</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomerFilmRentRecord, Integer> IDENTITY_CUSTOMER_FILM_RENT = Identities0.IDENTITY_CUSTOMER_FILM_RENT;
    public static final Identity<FilmRecord, Integer> IDENTITY_FILM = Identities0.IDENTITY_FILM;
    public static final Identity<FilmTypeRecord, Integer> IDENTITY_FILM_TYPE = Identities0.IDENTITY_FILM_TYPE;
    public static final Identity<PriceTypeRecord, Integer> IDENTITY_PRICE_TYPE = Identities0.IDENTITY_PRICE_TYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = UniqueKeys0.CUSTOMER_PKEY;
    public static final UniqueKey<CustomerFilmRentRecord> CUSTOMER_FILM_RENT_PKEY = UniqueKeys0.CUSTOMER_FILM_RENT_PKEY;
    public static final UniqueKey<FilmRecord> FILM_PKEY = UniqueKeys0.FILM_PKEY;
    public static final UniqueKey<FilmRecord> FILM_NAME_KEY = UniqueKeys0.FILM_NAME_KEY;
    public static final UniqueKey<FilmTypeRecord> FILM_TYPE_PKEY = UniqueKeys0.FILM_TYPE_PKEY;
    public static final UniqueKey<PriceTypeRecord> PRICE_TYPE_PKEY = UniqueKeys0.PRICE_TYPE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerFilmRentRecord, CustomerRecord> CUSTOMER_FILM_RENT__CUSTOMER_FILM_RENT_CUSTOMER_CODE_FKEY = ForeignKeys0.CUSTOMER_FILM_RENT__CUSTOMER_FILM_RENT_CUSTOMER_CODE_FKEY;
    public static final ForeignKey<CustomerFilmRentRecord, FilmRecord> CUSTOMER_FILM_RENT__CUSTOMER_FILM_RENT_FILM_ID_FKEY = ForeignKeys0.CUSTOMER_FILM_RENT__CUSTOMER_FILM_RENT_FILM_ID_FKEY;
    public static final ForeignKey<FilmRecord, FilmTypeRecord> FILM__FILM_FILM_TYPE_ID_FKEY = ForeignKeys0.FILM__FILM_FILM_TYPE_ID_FKEY;
    public static final ForeignKey<FilmTypeRecord, PriceTypeRecord> FILM_TYPE__FILM_TYPE_PRICE_TYPE_ID_FKEY = ForeignKeys0.FILM_TYPE__FILM_TYPE_PRICE_TYPE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CustomerFilmRentRecord, Integer> IDENTITY_CUSTOMER_FILM_RENT = createIdentity(CustomerFilmRent.CUSTOMER_FILM_RENT, CustomerFilmRent.CUSTOMER_FILM_RENT.ID);
        public static Identity<FilmRecord, Integer> IDENTITY_FILM = createIdentity(Film.FILM, Film.FILM.ID);
        public static Identity<FilmTypeRecord, Integer> IDENTITY_FILM_TYPE = createIdentity(FilmType.FILM_TYPE, FilmType.FILM_TYPE.ID);
        public static Identity<PriceTypeRecord, Integer> IDENTITY_PRICE_TYPE = createIdentity(PriceType.PRICE_TYPE, PriceType.PRICE_TYPE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = createUniqueKey(Customer.CUSTOMER, "customer_pkey", Customer.CUSTOMER.CODE);
        public static final UniqueKey<CustomerFilmRentRecord> CUSTOMER_FILM_RENT_PKEY = createUniqueKey(CustomerFilmRent.CUSTOMER_FILM_RENT, "customer_film_rent_pkey", CustomerFilmRent.CUSTOMER_FILM_RENT.ID);
        public static final UniqueKey<FilmRecord> FILM_PKEY = createUniqueKey(Film.FILM, "film_pkey", Film.FILM.ID);
        public static final UniqueKey<FilmRecord> FILM_NAME_KEY = createUniqueKey(Film.FILM, "film_name_key", Film.FILM.NAME);
        public static final UniqueKey<FilmTypeRecord> FILM_TYPE_PKEY = createUniqueKey(FilmType.FILM_TYPE, "film_type_pkey", FilmType.FILM_TYPE.ID);
        public static final UniqueKey<PriceTypeRecord> PRICE_TYPE_PKEY = createUniqueKey(PriceType.PRICE_TYPE, "price_type_pkey", PriceType.PRICE_TYPE.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CustomerFilmRentRecord, CustomerRecord> CUSTOMER_FILM_RENT__CUSTOMER_FILM_RENT_CUSTOMER_CODE_FKEY = createForeignKey(jooq.jooqobjects.Keys.CUSTOMER_PKEY, CustomerFilmRent.CUSTOMER_FILM_RENT, "customer_film_rent__customer_film_rent_customer_code_fkey", CustomerFilmRent.CUSTOMER_FILM_RENT.CUSTOMER_CODE);
        public static final ForeignKey<CustomerFilmRentRecord, FilmRecord> CUSTOMER_FILM_RENT__CUSTOMER_FILM_RENT_FILM_ID_FKEY = createForeignKey(jooq.jooqobjects.Keys.FILM_PKEY, CustomerFilmRent.CUSTOMER_FILM_RENT, "customer_film_rent__customer_film_rent_film_id_fkey", CustomerFilmRent.CUSTOMER_FILM_RENT.FILM_ID);
        public static final ForeignKey<FilmRecord, FilmTypeRecord> FILM__FILM_FILM_TYPE_ID_FKEY = createForeignKey(jooq.jooqobjects.Keys.FILM_TYPE_PKEY, Film.FILM, "film__film_film_type_id_fkey", Film.FILM.FILM_TYPE_ID);
        public static final ForeignKey<FilmTypeRecord, PriceTypeRecord> FILM_TYPE__FILM_TYPE_PRICE_TYPE_ID_FKEY = createForeignKey(jooq.jooqobjects.Keys.PRICE_TYPE_PKEY, FilmType.FILM_TYPE, "film_type__film_type_price_type_id_fkey", FilmType.FILM_TYPE.PRICE_TYPE_ID);
    }
}
