/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in video_rental_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>video_rental_schema.customer_film_rent_id_seq</code>
     */
    public static final Sequence<Integer> CUSTOMER_FILM_RENT_ID_SEQ = new SequenceImpl<Integer>("customer_film_rent_id_seq", VideoRentalSchema.VIDEO_RENTAL_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>video_rental_schema.film_id_seq</code>
     */
    public static final Sequence<Integer> FILM_ID_SEQ = new SequenceImpl<Integer>("film_id_seq", VideoRentalSchema.VIDEO_RENTAL_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>video_rental_schema.film_type_id_seq</code>
     */
    public static final Sequence<Integer> FILM_TYPE_ID_SEQ = new SequenceImpl<Integer>("film_type_id_seq", VideoRentalSchema.VIDEO_RENTAL_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>video_rental_schema.price_type_id_seq</code>
     */
    public static final Sequence<Integer> PRICE_TYPE_ID_SEQ = new SequenceImpl<Integer>("price_type_id_seq", VideoRentalSchema.VIDEO_RENTAL_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
