/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects;


import javax.annotation.Generated;

import jooq.jooqobjects.tables.Customer;
import jooq.jooqobjects.tables.CustomerFilmRent;
import jooq.jooqobjects.tables.Film;
import jooq.jooqobjects.tables.FilmType;
import jooq.jooqobjects.tables.PriceType;


/**
 * Convenience access to all tables in video_rental_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>video_rental_schema.customer</code>.
     */
    public static final Customer CUSTOMER = jooq.jooqobjects.tables.Customer.CUSTOMER;

    /**
     * The table <code>video_rental_schema.customer_film_rent</code>.
     */
    public static final CustomerFilmRent CUSTOMER_FILM_RENT = jooq.jooqobjects.tables.CustomerFilmRent.CUSTOMER_FILM_RENT;

    /**
     * The table <code>video_rental_schema.film</code>.
     */
    public static final Film FILM = jooq.jooqobjects.tables.Film.FILM;

    /**
     * The table <code>video_rental_schema.film_type</code>.
     */
    public static final FilmType FILM_TYPE = jooq.jooqobjects.tables.FilmType.FILM_TYPE;

    /**
     * The table <code>video_rental_schema.price_type</code>.
     */
    public static final PriceType PRICE_TYPE = jooq.jooqobjects.tables.PriceType.PRICE_TYPE;
}
