/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.jooqobjects.tables.Customer;
import jooq.jooqobjects.tables.CustomerFilmRent;
import jooq.jooqobjects.tables.Film;
import jooq.jooqobjects.tables.FilmType;
import jooq.jooqobjects.tables.PriceType;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VideoRentalSchema extends SchemaImpl {

    private static final long serialVersionUID = 1177506870;

    /**
     * The reference instance of <code>video_rental_schema</code>
     */
    public static final VideoRentalSchema VIDEO_RENTAL_SCHEMA = new VideoRentalSchema();

    /**
     * The table <code>video_rental_schema.customer</code>.
     */
    public final Customer CUSTOMER = jooq.jooqobjects.tables.Customer.CUSTOMER;

    /**
     * The table <code>video_rental_schema.customer_film_rent</code>.
     */
    public final CustomerFilmRent CUSTOMER_FILM_RENT = jooq.jooqobjects.tables.CustomerFilmRent.CUSTOMER_FILM_RENT;

    /**
     * The table <code>video_rental_schema.film</code>.
     */
    public final Film FILM = jooq.jooqobjects.tables.Film.FILM;

    /**
     * The table <code>video_rental_schema.film_type</code>.
     */
    public final FilmType FILM_TYPE = jooq.jooqobjects.tables.FilmType.FILM_TYPE;

    /**
     * The table <code>video_rental_schema.price_type</code>.
     */
    public final PriceType PRICE_TYPE = jooq.jooqobjects.tables.PriceType.PRICE_TYPE;

    /**
     * No further instances allowed
     */
    private VideoRentalSchema() {
        super("video_rental_schema", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CUSTOMER_FILM_RENT_ID_SEQ,
            Sequences.FILM_ID_SEQ,
            Sequences.FILM_TYPE_ID_SEQ,
            Sequences.PRICE_TYPE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            CustomerFilmRent.CUSTOMER_FILM_RENT,
            Film.FILM,
            FilmType.FILM_TYPE,
            PriceType.PRICE_TYPE);
    }
}
