/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.jooqobjects.Keys;
import jooq.jooqobjects.VideoRentalSchema;
import jooq.jooqobjects.tables.records.FilmTypeRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmType extends TableImpl<FilmTypeRecord> {

    private static final long serialVersionUID = -1945182595;

    /**
     * The reference instance of <code>video_rental_schema.film_type</code>
     */
    public static final FilmType FILM_TYPE = new FilmType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FilmTypeRecord> getRecordType() {
        return FilmTypeRecord.class;
    }

    /**
     * The column <code>video_rental_schema.film_type.id</code>.
     */
    public final TableField<FilmTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('video_rental_schema.film_type_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>video_rental_schema.film_type.name</code>.
     */
    public final TableField<FilmTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>video_rental_schema.film_type.number_days_with_same_price</code>.
     */
    public final TableField<FilmTypeRecord, Integer> NUMBER_DAYS_WITH_SAME_PRICE = createField("number_days_with_same_price", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>video_rental_schema.film_type.default_bonus_points</code>.
     */
    public final TableField<FilmTypeRecord, Integer> DEFAULT_BONUS_POINTS = createField("default_bonus_points", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>video_rental_schema.film_type.price_type_id</code>.
     */
    public final TableField<FilmTypeRecord, Integer> PRICE_TYPE_ID = createField("price_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>video_rental_schema.film_type</code> table reference
     */
    public FilmType() {
        this("film_type", null);
    }

    /**
     * Create an aliased <code>video_rental_schema.film_type</code> table reference
     */
    public FilmType(String alias) {
        this(alias, FILM_TYPE);
    }

    private FilmType(String alias, Table<FilmTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private FilmType(String alias, Table<FilmTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VideoRentalSchema.VIDEO_RENTAL_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FilmTypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FILM_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FilmTypeRecord> getPrimaryKey() {
        return Keys.FILM_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FilmTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<FilmTypeRecord>>asList(Keys.FILM_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<FilmTypeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FilmTypeRecord, ?>>asList(Keys.FILM_TYPE__FILM_TYPE_PRICE_TYPE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmType as(String alias) {
        return new FilmType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FilmType rename(String name) {
        return new FilmType(name, null);
    }
}
