/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.jooqobjects.Keys;
import jooq.jooqobjects.VideoRentalSchema;
import jooq.jooqobjects.tables.records.PriceTypeRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriceType extends TableImpl<PriceTypeRecord> {

    private static final long serialVersionUID = 371889811;

    /**
     * The reference instance of <code>video_rental_schema.price_type</code>
     */
    public static final PriceType PRICE_TYPE = new PriceType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PriceTypeRecord> getRecordType() {
        return PriceTypeRecord.class;
    }

    /**
     * The column <code>video_rental_schema.price_type.id</code>.
     */
    public final TableField<PriceTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('video_rental_schema.price_type_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>video_rental_schema.price_type.name</code>.
     */
    public final TableField<PriceTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>video_rental_schema.price_type.value</code>.
     */
    public final TableField<PriceTypeRecord, BigDecimal> VALUE = createField("value", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * Create a <code>video_rental_schema.price_type</code> table reference
     */
    public PriceType() {
        this("price_type", null);
    }

    /**
     * Create an aliased <code>video_rental_schema.price_type</code> table reference
     */
    public PriceType(String alias) {
        this(alias, PRICE_TYPE);
    }

    private PriceType(String alias, Table<PriceTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private PriceType(String alias, Table<PriceTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VideoRentalSchema.VIDEO_RENTAL_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PriceTypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PRICE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PriceTypeRecord> getPrimaryKey() {
        return Keys.PRICE_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PriceTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<PriceTypeRecord>>asList(Keys.PRICE_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceType as(String alias) {
        return new PriceType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PriceType rename(String name) {
        return new PriceType(name, null);
    }
}
